# Generated by Django 5.2 on 2025-04-24 21:24

import Edahiras.utils
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dahiras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_dahira",
                    models.CharField(default="Dahira Tidiane", max_length=150),
                ),
                ("siege", models.CharField(default="Siege", max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        default="media/audio/defaut.ogg",
                        help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                        upload_to="media/image/",
                        validators=[Edahiras.utils.validate_image_file],
                    ),
                ),
                ("date_creation", models.DateField(auto_now=True)),
                (
                    "description",
                    models.CharField(default="description", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Localites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_localite", models.CharField(max_length=200)),
                (
                    "dahira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localites",
                        to="Edahiras.dahiras",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_section", models.CharField(max_length=200)),
                (
                    "localite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="Edahiras.localites",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("biography", models.TextField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                        null=True,
                        upload_to="media/image/",
                        validators=[Edahiras.utils.validate_image_file],
                    ),
                ),
                ("date_inscription", models.DateField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("auditeur", "Auditeur"),
                            ("admin", "Administrateur"),
                            ("conferencier", "Conferencier"),
                        ],
                        default="auditeur",
                        max_length=100,
                    ),
                ),
                (
                    "dahira",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="Edahiras.dahiras",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=200)),
                ("chapitre", models.CharField(max_length=200)),
                ("sequence", models.CharField(max_length=200)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        default="media/audio/defaut.ogg",
                        help_text="Fichier audio au format MP3, WAV, OGG ou M4A (max. 20 MB)",
                        null=True,
                        upload_to="media/audio/",
                        validators=[Edahiras.utils.validate_audio_file],
                    ),
                ),
                (
                    "image_audio",
                    models.ImageField(
                        default="media/image/default.jpeg",
                        help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                        upload_to="media/image/",
                        validators=[Edahiras.utils.validate_image_file],
                    ),
                ),
                ("date_audio", models.DateField(auto_now=True)),
                ("duree", models.PositiveIntegerField(default=0)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
