# Generated by Django 5.2 on 2025-05-27 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Edahiras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="sequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio",
                to="Edahiras.sequence",
            ),
        ),
    ]
