# Generated by Django 5.2 on 2025-04-24 21:29

import Edahiras.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Edahiras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dahiras",
            name="logo",
            field=models.ImageField(
                default="media/image/default.jpeg",
                help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                upload_to="media/image/",
                validators=[Edahiras.utils.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="membres",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="media/image/default.jpeg",
                help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                null=True,
                upload_to="media/image/",
                validators=[Edahiras.utils.validate_image_file],
            ),
        ),
    ]
