# Generated by Django 5.2 on 2025-05-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edahiras', '0002_alter_audio_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='chapitre',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='Edahiras.theme'),
        ),
    ]
