# Generated by Django 5.2 on 2025-04-24 21:36

import Edahiras.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Edahiras", "0002_alter_dahiras_logo_alter_membres_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio_file",
            field=models.FileField(
                blank=True,
                default="audio/defaut.ogg",
                help_text="Fichier audio au format MP3, WAV, OGG ou M4A (max. 20 MB)",
                null=True,
                upload_to="media/audio/",
                validators=[Edahiras.utils.validate_audio_file],
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="image_audio",
            field=models.ImageField(
                default="image/default.jpeg",
                help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                upload_to="media/image/",
                validators=[Edahiras.utils.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="dahiras",
            name="logo",
            field=models.ImageField(
                default="image/default.jpeg",
                help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                upload_to="media/image/",
                validators=[Edahiras.utils.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="membres",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="image/default.jpeg",
                help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                null=True,
                upload_to="media/image/",
                validators=[Edahiras.utils.validate_image_file],
            ),
        ),
    ]
