# Generated by Django 5.2 on 2025-04-26 16:13

import Edahiras.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Edahiras", "0003_alter_audio_audio_file_alter_audio_image_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="Fichier audio au format MP3, WAV, OGG ou M4A (max. 20 MB)",
                null=True,
                upload_to="media/audio/",
                validators=[Edahiras.utils.validate_audio_file],
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="image_audio",
            field=models.ImageField(
                help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                upload_to="media/image/",
                validators=[Edahiras.utils.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="sequence",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="dahiras",
            name="logo",
            field=models.ImageField(
                help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                upload_to="media/image/",
                validators=[Edahiras.utils.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="dahiras",
            name="nom_dahira",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="dahiras",
            name="siege",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="membres",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Image au format JPG, JPEG, PNG ou GIF (max. 5 MB)",
                null=True,
                upload_to="media/image/",
                validators=[Edahiras.utils.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="membres",
            name="role",
            field=models.CharField(
                choices=[
                    ("auditeur", "Auditeur"),
                    ("admin", "Administrateur"),
                    ("conferencier", "Conferencier"),
                ],
                max_length=100,
            ),
        ),
    ]
