# Generated by Django 5.2 on 2025-05-30 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edahiras', '0003_remove_theme_chapitre_chapitre_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='Edahiras.chapitre'),
        ),
    ]
