# Generated by Django 5.2 on 2025-04-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Edahiras", "0004_alter_audio_audio_file_alter_audio_image_audio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audio",
            name="duree",
        ),
    ]
