# Generated by Django 5.2 on 2025-05-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edahiras', '0004_sequence_chapitre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='chapitre',
            name='sequence',
        ),
    ]
