# Generated by Django 5.2 on 2025-05-31 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edahiras', '0005_remove_audio_theme_remove_chapitre_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to=settings.AUTH_USER_MODEL),
        ),
    ]
