# Generated by Django 5.2 on 2025-06-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edahiras', '0008_alter_audio_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='auteur',
        ),
    ]
