# Generated by Django 5.2 on 2025-06-01 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edahiras', '0010_chapitre_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='Edahiras.theme'),
        ),
    ]
