# Generated by Django 5.2 on 2025-06-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edahiras', '0011_audio_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='auteur',
        ),
    ]
