# Generated by Django 5.2 on 2025-06-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edahiras', '0013_chapitre_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='auteur',
        ),
    ]
